In [1]:
# Writen by liupu -- 2019.4.10
# Need to install numpy, sklearn
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()
data=iris.data      #data_x
target=iris.target  #data_y
labels=iris.feature_names #feature_name

In [3]:
print(labels)
print(data.shape)
print(data[:10])
print(target.shape)
print(target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
train_y = np.append(np.append(target[:40], target[50:90]), target[100:140])
train_x = np.append(np.append(data[:40,], data[50:90,], axis=0), data[100:140,], axis=0)
test_y = np.append(np.append(target[40:50], target[90:100]), target[140:150])
test_x = np.append(np.append(data[40:50], data[90:100], axis=0), data[140:150], axis=0)

In [5]:
print(train_x.shape, train_y.shape)
print(test_x.shape, test_y.shape)
print(test_y)

(120, 4) (120,)
(30, 4) (30,)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]


In [6]:
class Knn():
    def __init__(self, database, k=5):
        self._database = database
        self._x = database[0]
        self._y = database[1]
        self._xshape = database[0].shape
        self._yshape = database[1].shape
        self._k = k
    
    def distance(self, x1, x2):
        x1 = x1.reshape(-1)             #flatten x1
        x2 = x2.reshape(-1)             #flatten x2
        return np.sum((x2-x1)**2)              #return the L2 distance between x1 and x2
    
    def predict(self, x):
        assert self._xshape[1:] == x.shape[1:]
        predict_y = np.zeros(x.shape[0])
        for j, item in enumerate(x):
            dist = np.zeros([self._yshape[0], 2])       #a row present [distance, y]
            vote = np.zeros(self._yshape[0])
            for i, xi in enumerate(self._x):
                dist[i] = [self.distance(xi, item), self._y[i]]
            dist = dist[dist[:,0].argsort()]         #sort by col_1(col of distance)
            for i in range(self._k):
                vote[int(dist[i][1])] += 1
            predict_y[j] = np.argmax(vote)          #get the index of maximum of vote
        return predict_y.astype(int)            

In [7]:
knn = Knn((train_x,train_y), k=3)
y = knn.predict(test_x)

In [8]:
print(y)
print(test_y)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
